// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IBook is an autogenerated mock type for the IBook type
type IBook struct {
	mock.Mock
}

// GetAuthor provides a mock function with given fields:
func (_m *IBook) GetAuthor() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetBookNamesWithInterface provides a mock function with given fields:
func (_m *IBook) GetBookNamesWithInterface() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

type mockConstructorTestingTNewIBook interface {
	mock.TestingT
	Cleanup(func())
}

// NewIBook creates a new instance of IBook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIBook(t mockConstructorTestingTNewIBook) *IBook {
	mock := &IBook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
