// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ITestMethod is an autogenerated mock type for the ITestMethod type
type ITestMethod struct {
	mock.Mock
}

// TestWithInterface provides a mock function with given fields: val
func (_m *ITestMethod) TestWithInterface(val string) {
	_m.Called(val)
}

type mockConstructorTestingTNewITestMethod interface {
	mock.TestingT
	Cleanup(func())
}

// NewITestMethod creates a new instance of ITestMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITestMethod(t mockConstructorTestingTNewITestMethod) *ITestMethod {
	mock := &ITestMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
